/* Auto-generated by gen_primes.c - do not edit. */
#ifndef PRIMES_TABLE_H
#define PRIMES_TABLE_H

#define PRIMES_LIMIT 1000000UL
#define PRIMES_COUNT 78498UL

extern const unsigned int primes[PRIMES_COUNT];

#endif /* PRIMES_TABLE_H */
